### ISSUE TITLE
TinyLlama issue in latest WIP branch

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1079]
There seems to be an issue with the TinyLlama configs in the latest WIP branch:

```bash
⚡ download-docs ~/lit-gpt export repo_id=TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
⚡ download-docs ~/lit-gpt python chat/base.py --checkpoint_dir checkpoints/$repo_id
Traceback (most recent call last):
  File "chat/base.py", line 380, in <module>
    CLI(main)
  File "/teamspace/studios/this_studio/lit-gpt/lit_gpt/utils.py", line 379, in CLI
    return CLI(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/jsonargparse/_cli.py", line 193, in _run_component
    return component(**cfg)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "chat/base.py", line 140, in main
    config = Config.from_json(checkpoint_dir / "lit_config.json")
  File "/teamspace/studios/this_studio/lit-gpt/lit_gpt/config.py", line 124, in from_json
    return cls(**json_kwargs)
TypeError: __init__() got an unexpected keyword argument 'norm_class_name'
⚡ download-docs ~/lit-gpt 
```

**Comment by carmocca** [comment]
Looks to me like you are trying to load a wip-branch config into the main-branch code

**Comment by rasbt** [comment]
arg yes my bad, sorry!
