### ISSUE TITLE
Issues with TinyStories

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1085]
I tried to pretrain with TinyStories several times, and it always seems to abort around 29%:

```
python litgpt/pretrain.py \
  --data litgpt.data.TinyStories \
  --model_name tiny-llama-1.1b \
  --tokenizer_dir checkpoints/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T/
```

```
 29%|███████████████████████████████                                                                              | 28508/100000 [00:49<01:55, 616.94it/s]


 29%|███████████████████████████████▉                                                                             | 29330/100000 [00:51<03:45, 313.37it/s]Done.██████████████████████████████▌                                                                              | 28019/100000 [00:50<04:04, 294.57it/s]
Traceback (most recent call last):█                                                                               | 27532/100000 [00:50<03:54, 308.75it/s]
  File "litgpt/pretrain.py", line 381, in <module>                                                                | 29038/100000 [00:51<02:40, 440.86it/s]
    CLI(setup)
  File "/teamspace/studios/this_studio/lit-gpt/litgpt/utils.py", line 399, in CLI                                 | 28618/100000 [00:50<03:36, 329.98it/s]
    return CLI(*args, **kwargs)████                                                                               | 27578/100000 [00:50<03:37, 333.52it/s]
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/jsonargparse/_cli.py", line 96, in CLI  | 28467/100000 [00:50<03:56, 301.86it/s]
    return _run_component(components, cfg_init)                                                                   | 27765/100000 [00:50<03:42, 324.88it/s]
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/jsonargparse/_cli.py", line 193, in _run_component0000 [00:50<02:53, 419.04it/s]
    return component(**cfg)████████▏                                                                              | 27640/100000 [00:50<03:44, 321.76it/s]
  File "litgpt/pretrain.py", line 90, in setup                                                                    | 27986/100000 [00:50<03:34, 336.14it/s]
    main(fabric, devices, seed, resume, config, data, out_dir, tokenizer_dir, tokenizer, train, eval)             | 27917/100000 [00:50<03:47, 316.19it/s]
  File "litgpt/pretrain.py", line 137, in main                                                                    | 27984/100000 [00:50<03:30, 342.61it/s]
    train_dataloader, val_dataloader = get_dataloaders(fabric, data, tokenizer, train, model.max_seq_length)      | 27595/100000 [00:50<02:55, 412.92it/s]
  File "litgpt/pretrain.py", line 319, in get_dataloaders                                                         | 27685/100000 [00:50<03:49, 314.98it/s]
    data.setup()██████████████████▉                                                                               | 27450/100000 [00:50<03:42, 326.29it/s]
  File "/teamspace/studios/this_studio/lit-gpt/litgpt/data/tinystories.py", line 57, in setup                     | 28620/100000 [00:50<02:43, 437.59it/s]
    assert len(shard_filenames) > 0, f"No bin files found in {bin_dir}"                                           | 27474/100000 [00:50<03:05, 391.62it/s]
AssertionError: No bin files found in data/TinyStories_all_data                                                   | 27420/100000 [00:50<04:16, 283.08it/s]
⚡ upd-prints ~/lit-gpt python litgpt/pretrain.py --data litgpt.data.TinyStories
```

For some reason, I can't neatly copy the terminal output because of the progress bars. It does show "done" every time though:

<img width="736" alt="Screenshot 2024-03-11 at 4 40 44 PM" src="https://github.com/Lightning-AI/litgpt/assets/5618407/c456ed16-1edc-476a-b534-858a852bf28c">

**Comment by carmocca** [comment]
The `ProcessPoolExecutor` used by Karpathy is very finicky (https://github.com/karpathy/llama2.c/blob/master/tinystories.py#L170-L171). It's probably best to implement #995

What does `ls data/TinyStories_all_data` print?

**Comment by rasbt** [comment]
It looks like all 50 shard are there, actually 🤔:

```
 ls -lh data/TinyStories_all_data 
total 6.5G
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data00.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data01.json
-rw-r--r-- 1 sebastian sebastian 135M May 17  2023 data02.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data03.json
-rw-r--r-- 1 sebastian sebastian 135M May 17  2023 data04.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data05.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data06.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data07.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data08.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data09.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data10.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data11.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data12.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data13.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data14.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data15.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data16.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data17.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data18.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data19.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data20.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data21.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data22.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data23.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data24.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data25.json
-rw-r--r-- 1 sebastian sebastian 135M May 17  2023 data26.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data27.json
-rw-r--r-- 1 sebastian sebastian 135M May 17  2023 data28.json
-rw-r--r-- 1 sebastian sebastian 135M May 17  2023 data29.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data30.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data31.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data32.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data33.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data34.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data35.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data36.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data37.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data38.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data39.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data40.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data41.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data42.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data43.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data44.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data45.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data46.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data47.json
-rw-r--r-- 1 sebastian sebastian 134M May 17  2023 data48.json
-rw-r--r-- 1 sebastian sebastian  91M May 17  2023 data49.json
```

**Comment by carmocca** [comment]
The jsons are the "raw data". Tokenization produces `.bin` files which are not there as they should. Rerunning the script should start tokenization again. You can try tweaking the `ProcessPoolExecutor(max_workers=N)` value in https://github.com/Lightning-AI/litgpt/blob/wip/litgpt/data/tinystories.py#L151 if it's overloading your system

**Comment by rasbt** [comment]
I eventually got it to work by lowering the max workers like you suggested. Thanks!
