### ISSUE TITLE
Error running Gemma Finetuning with lora

### ISSUE THREAD

**Issue by vabatista** [Lightning-AI/litgpt#1176]
I'm having trouble using google gemma model.  Steps to reproduce.

1. I created a fresh conda env and install litgpt using `pip install 'litgpt[all]'`
2. I downloaded the `gemma-7b-it` model with default options
3. Tried to run finetuning with Alpaca Dataset.
`litgpt finetune lora   --checkpoint_dir saved-models/google/gemma-7b-it/   --data Alpaca2k   --out_dir out/gemma-2-lora`

But I'm getting this error:

``` 
Traceback (most recent call last):      
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/bin/litgpt", line 8, in <module>
    sys.exit(main())                                                                                                                                                                                        
             ^^^^^^                              
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/__main__.py", line 129, in main
    fn(**kwargs)                                                                                                                                                                                            
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/finetune/lora.py", line 138, in setup
    fabric.launch(main, devices, seed, config, data, checkpoint_dir, out_dir, train, eval)
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 866, in launch     
    return self._wrap_and_launch(function, self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 952, in _wrap_and_launch
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 957, in _wrap_with_setup   
    return to_run(*args, **kwargs)         
           ^^^^^^^^^^^^^^^^^^^^^^^         
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/finetune/lora.py", line 192, in main          
    fit(                                
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/finetune/lora.py", line 244, in fit
    validate(fabric, model, val_dataloader, tokenizer, dataclasses.replace(eval, max_iters=2), data)  # sanity check          
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)                                                                                                                                                                            
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/finetune/lora.py", line 340, in validate
    logits = model(input_ids)                                                                         
             ^^^^^^^^^^^^^^^^         
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/lightning/fabric/wrappers.py", line 143, in forward
    output = self._forward_module(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/lora.py", line 545, in forward
    x = block(x, cos, sin, mask, input_pos)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/model.py", line 158, in forward
    h = self.attn(n_1, cos, sin, mask, input_pos)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/model.py", line 197, in forward
    qkv = self.attn(x)
          ^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/lora.py", line 432, in forward
    lora = self.zero_pad(after_B) * self.scaling  # (64, 64, 256) after zero_pad (64, 64, 384)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vabatista/mambaforge-pypy3/envs/sesame2/lib/python3.11/site-packages/litgpt/lora.py", line 339, in zero_pad
    result = result.index_copy(
             ^^^^^^^^^^^^^^^^^^
IndexError: index_copy_(): Number of indices (8192) should be equal to source.size(dim) (6144)

```

**Comment by vabatista** [comment]
Duplicated of  #1124
