### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'microsoft/phi-2/lit_model.pth'

### ISSUE THREAD

**Issue by Alamoalone** [Lightning-AI/litgpt#1497]
```bash
Epoch 6 | iter 2501 step 156 | loss train: 0.865, val: 1.035 | iter time: 55756.61 ms
Training time: 58117.91s
Validating ...
Final evaluation | val loss: 0.949 | val ppl: 2.583
Saving LoRA weights to 'out/phi-2-finetuned/final/lit_model.pth.lora'
{'checkpoint_dir': PosixPath('out/phi-2-finetuned/final'),
 'precision': None,
 'pretrained_checkpoint_dir': None}
Traceback (most recent call last):
  File "/users/pgrad/wangx33/.venv/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litgpt/__main__.py", line 57, in main
    CLI(parser_data)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/jsonargparse/_cli.py", line 119, in CLI
    return _run_component(component, init.get(subcommand))
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/jsonargparse/_cli.py", line 196, in _run_component
    return component(**cfg)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litgpt/finetune/lora.py", line 146, in setup
    fabric.launch(main, devices, seed, config, data, checkpoint_dir, out_dir, train, eval, optimizer)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 845, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 931, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 936, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litgpt/finetune/lora.py", line 228, in main
    merge_lora(checkpoint_dir=save_path.parent)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litgpt/scripts/merge_lora.py", line 61, in merge_lora
    pretrained_checkpoint = torch.load(str(pretrained_checkpoint_dir / "lit_model.pth"), mmap=True)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'microsoft/phi-2/lit_model.pth'
```

**Comment by rasbt** [comment]
Thanks for reporting. Hm, that's a weird one ... have you perhaps moved the original checkpoint folder after starting the finetuning?

**Comment by Alamoalone** [comment]
I used 0.4.0 dev before, but I upgraded it to 0.4.1 and finetuned it successful.

**Comment by rasbt** [comment]
glad to hear that this solved it!
