### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'nvidia-smi'

### ISSUE THREAD

**Issue by Alamoalone** [Lightning-AI/litgpt#1503]
### When I deploy the finetuned model , it happened.

**03:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. Integrated Matrox G200eW3 Graphics Controller (rev 04)**

(.venv) wangx33@elektra:~/Final_Project$ litgpt serve out/phi-2-finetuned/final
{'accelerator': 'auto',
 'checkpoint_dir': PosixPath('out/phi-2-finetuned/final'),
 'devices': 1,
 'max_new_tokens': 50,
 'port': 8000,
 'precision': None,
 'stream': False,
 'temperature': 0.8,
 'top_k': 200,
 'top_p': 1.0}
Traceback (most recent call last):
  File "/users/pgrad/wangx33/.venv/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litgpt/__main__.py", line 57, in main
    CLI(parser_data)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/jsonargparse/_cli.py", line 119, in CLI
    return _run_component(component, init.get(subcommand))
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/jsonargparse/_cli.py", line 196, in _run_component
    return component(**cfg)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litgpt/deploy/serve.py", line 217, in run_server
    server = LitServer(
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litserve/server.py", line 336, in __init__
    self._connector = _Connector(accelerator=accelerator, devices=devices)
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litserve/connector.py", line 33, in __init__
    self._accelerator = self._choose_auto_accelerator()
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litserve/connector.py", line 63, in _choose_auto_accelerator
    gpu_backend = self._choose_gpu_accelerator_backend()
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litserve/connector.py", line 77, in _choose_gpu_accelerator_backend
    if check_cuda_with_nvidia_smi() > 0:
  File "/users/pgrad/wangx33/.venv/lib/python3.9/site-packages/litserve/connector.py", line 92, in check_cuda_with_nvidia_smi
    nvidia_smi_output = subprocess.check_output(["nvidia-smi", "-L"]).decode("utf-8").strip()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'nvidia-smi'

**Comment by rasbt** [comment]
Hm, not sure why this might happen. @aniketmaurya do you know whether LitServe works on/supports Windows in general?

**Comment by aniketmaurya** [comment]
Hi @rasbt, yes, ideally LitServe should work on Windows (although it is not as battle-tested as Linux-based OS).
@Alamoalone, could you please check if you have permission to call nvidia-smi from the user account you're trying to serve from?

**Comment by Alamoalone** [comment]
After I asked the administrator to try running it, he informed me of the reason for not having a GPU. After running from scratch on Colab, I successfully completed it. I don't know if this provides any clues. @aniketmaurya

**Comment by rasbt** [comment]
Thanks for reporting back! So it seemed that maybe a GPU device was installed but maybe not made available, which is why the `accelerator="auto"` setting perhaps failed. In this case you could try the following on the first machine that had the problem:

```bash
litgpt serve out/phi-2-finetuned/final accelerator="cpu"
```

Please let us know in case there are still issue, and we could revisit this.

**Comment by Alamoalone** [comment]
(.venv) wangx33@elektra:~/Final_Project$ litgpt serve out/phi-2-finetuned/final accelerator="cpu"
usage: litgpt [options] serve [-h] [--config CONFIG] [--print_config[=flags]] [--precision PRECISION] [--temperature TEMPERATURE]
                              [--top_k TOP_K] [--top_p TOP_P] [--max_new_tokens MAX_NEW_TOKENS] [--devices DEVICES]
                              [--accelerator ACCELERATOR] [--port PORT] [--stream {true,false}]
                              checkpoint_dir
error: Unrecognized arguments: accelerator=cpu

HI, @rasbt I tried this command , here is the log

**Comment by rasbt** [comment]
Sorry it was late and I was probably tired. It should have been `--accelerator` 😅

```bash
litgpt serve checkpoints/EleutherAI/pythia-160m_2 --accelerator cpu
```

**Comment by Alamoalone** [comment]
Hi, @rasbt , How to  modify default address?

INFO:     Started server process [4130248]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

**Comment by Alamoalone** [comment]
Hi, @aniketmaurya , it's working, thanks a lot.
<img width="630" alt="image" src="https://github.com/Lightning-AI/litgpt/assets/13886204/fe5c5291-ba3f-49f7-9ba5-c9fff91083b9">
