### ISSUE TITLE
Chat: doesn't work with enabled `compilation`

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/litgpt#1584]
### Bug description

Hi there 👋 

With the code from the main when running chat with enabled compilation
```bash
litgpt chat microsoft/Phi-3-mini-4k-instruct --compile=True
```

and entering any prompt, this error occurs:
```text
AssertionError: Global state changed while dynamo tracing, please report a bug
```

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.4.3.dev0
```

**Comment by Borda** [comment]
Seems I canot start it now, the same command gives the following on the main branch:
```
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/teamspace/studios/this_studio/litgpt | repo/litgpt/__main__.py", line 69, in main
    CLI(parser_data)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 23, in CLI
    return auto_cli(*args, _stacklevel=3, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 125, in auto_cli
    return _run_component(component, init.get(subcommand))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 210, in _run_component
    return component(**cfg)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/teamspace/studios/this_studio/litgpt | repo/litgpt/chat/base.py", line 240, in main
    next_token = torch.compile(next_token, mode="reduce-overhead", dynamic=True)
NameError: name 'next_token' is not defined
```
