### ISSUE TITLE
did not convert the model to litgpt format, why?

### ISSUE THREAD

**Issue by Esmail-ibraheem** [Lightning-AI/litgpt#1615]
### Bug description

tried to download the CohereForAI/aya-23-8B model using `litgpt download model_name`

and then tried to convert hf to litgpt using `litgpt convert_to_litgpt checkpoints_1/CohereForAI/aya-23-8B`

but this is what happened: 

it says `ValueError: 'aya-23-8B' is not a supported config name`

```
esmaeil@ESMAEIL:~/Desktop/llm$ litgpt convert_to_litgpt checkpoints_1/CohereForAI/aya-23-8B
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
{'checkpoint_dir': PosixPath('checkpoints_1/CohereForAI/aya-23-8B'),
 'debug_mode': False,
 'dtype': None,
 'model_name': None}
Traceback (most recent call last):
  File "/home/esmaeil/.local/lib/python3.10/site-packages/litgpt/config.py", line 99, in from_name
    conf_dict = next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esmaeil/.local/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/home/esmaeil/.local/lib/python3.10/site-packages/litgpt/__main__.py", line 71, in main
    CLI(parser_data)
  File "/home/esmaeil/.local/lib/python3.10/site-packages/jsonargparse/_cli.py", line 119, in CLI
    return _run_component(component, init.get(subcommand))
  File "/home/esmaeil/.local/lib/python3.10/site-packages/jsonargparse/_cli.py", line 204, in _run_component
    return component(**cfg)
  File "/home/esmaeil/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/esmaeil/.local/lib/python3.10/site-packages/litgpt/scripts/convert_hf_checkpoint.py", line 401, in convert_hf_checkpoint
    config = Config.from_name(model_name)
  File "/home/esmaeil/.local/lib/python3.10/site-packages/litgpt/config.py", line 105, in from_name
    raise ValueError(f"{name!r} is not a supported config name")
ValueError: 'aya-23-8B' is not a supported config name
```

## the model:
![Screenshot from 2024-07-23 11-48-01](https://github.com/user-attachments/assets/5266b4fd-865e-4987-b30a-80d5dd141c5e)

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.4.5



```

**Comment by rasbt** [comment]
Thanks for the note. I believe this is because that's a model that's currently not supported. The list of supported models can be obtained via

```
litgpt download list
```

If the model is not listed there, then the configuration is not implemented/supported. 

Maybe we need to add a function to check whether the model someone tries to download is in this list to avoid this issue.

**Comment by Esmail-ibraheem** [comment]
ok but i want this model, can you add it to the supported list ?!

**Comment by rasbt** [comment]
Currently I may not have the capacity to add it (I have a long list of other things to get to first), but I recently wrote up the procedure for adding new models in case you'd like to contribute this as a PR: https://github.com/Lightning-AI/litgpt/blob/main/tutorials/developer-docs/adding-models.md
