### ISSUE TITLE
zsh: illegal hardware instruction

### ISSUE THREAD

**Issue by Suddhasatwa** [Lightning-AI/litgpt#1706]
### Bug description

the library does not seem to work on Macbook Air.
the sample code and the error is as follows:

```(venv) (base) suddhasatwa@Suddhasatwas-MacBook-Air LLM % ipython
Python 3.10.9 (main, Mar  1 2023, 12:33:47) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from litgpt import LLM
   ...: 
   ...: llm = LLM.load("microsoft/phi-2")
   ...: text = llm.generate("Correct the spelling: Every summer, the familly enjoys a trip to the mountains.")
   ...: print(text)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/suddhasatwa/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/terminal/ipapp.py", line 318, in start
    self.shell.mainloop()
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 720, in mainloop
    self.interact()
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/terminal/interactiveshell.py", line 713, in interact
    self.run_cell(code, store_history=True)
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2961, in run_cell
    result = self._run_cell(
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3016, in _run_cell
    result = runner(coro)
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3221, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3400, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/suddhasatwa/anaconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-e37cf006e276>", line 1, in <module>
    from litgpt import LLM
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/litgpt/__init__.py", line 6, in <module>
    from litgpt.api import LLM
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/litgpt/api.py", line 11, in <module>
    import torch
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/suddhasatwa/Documents/LLM/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
zsh: illegal hardware instruction  ipython```


### What operating system are you using?

macOS

### LitGPT Version

```(venv) (base) suddhasatwa@Suddhasatwas-MacBook-Air LLM % pip show litgpt | grep Version:
Version: 0.4.11```

**Comment by Andrei-Aksionov** [comment]
Hello @Suddhasatwa 

It seems that you've copied not only the code from the code-block, but also it's formatting: print(text)```
(Notice three backticks at the end.)

You can even see it in the error message:
```text
zsh: illegal hardware instruction  ipython```
```

**Comment by Suddhasatwa** [comment]
@Andrei-Aksionov : That's a formatting issue in my comment or in this ticket, not in my code!!
Adding ``` does not cause an error related to 

``` device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),```

Please reopen this ticket and advise.

**Comment by Suddhasatwa** [comment]
I have now updated the ticket description for clarity

**Comment by Andrei-Aksionov** [comment]
I ran the code on my MacBook and got different error:
```text
The operator 'aten::index_copy.out' is not currently implemented for the MPS device.
```
This is an already reported issue: #1655 

Not sure why you have a different erorr.
I believe that support of MPS devices is not a priority right now. 
@rasbt Could you comment on that? 

Anyway, I think support of MPS devices should be considered (if changes won't hurt perf on Linux machines)

**Comment by rasbt** [comment]
> I ran the code on my MacBook and got different error:

I can confirm this error (coincidentally filed this earlier here: #1714 ). I thought it was related to recent KV cache changes but may have existed earlier. Have to look into it more.

The other issue is that some recent commits have also broken CPU support #1715 .

**Comment by rasbt** [comment]
As of the most recent release (v0.4.12), litgpt should work again on macOS. You can either install the latest version from main or do

```bash
pip install litgpt -U
```

Then, e.g.,

```python
from litgpt import LLM

llm = LLM.load("microsoft/phi-2")
llm.generate("What do Llamas eat?")
```

will produce reasonable results again. (There was an issue with the default precision on macOS.)
