### ISSUE TITLE
Manual convert_to_litgpt for Phi-3.5-mini-instruct downloaded weights from HF

### ISSUE THREAD

**Issue by wasifferoze** [Lightning-AI/litgpt#1711]
### Bug description

When I manual covert Phi-3.5-mini-instruct weights downloaded from HF by clone repository, I get this error. this is command I used ` litgpt convert_to_litgpt checkpoints/microsoft/Phi-3.5-mini-instruct --model_name Phi-3.5-mini-instruct`
This is error output
`(ptl-py310) root@49a44a90ed1b:~/data1# litgpt convert_to_litgpt checkpoints/microsoft/Phi-3.5-mini-instruct --model_name Phi-3.5-mini-instruct
uvloop is not installed. Falling back to the default asyncio event loop.
{'checkpoint_dir': PosixPath('checkpoints/microsoft/Phi-3.5-mini-instruct'),
 'debug_mode': False,
 'dtype': None,
 'model_name': 'Phi-3.5-mini-instruct'}
Traceback (most recent call last):
  File "/opt/conda/envs/ptl-py310/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/litgpt/__main__.py", line 71, in main
    CLI(parser_data)
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/jsonargparse/_cli.py", line 119, in CLI
    return _run_component(component, init.get(subcommand))
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/jsonargparse/_cli.py", line 204, in _run_component
    return component(**cfg)
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/litgpt/scripts/convert_hf_checkpoint.py", line 525, in convert_hf_checkpoint
    total_size = max(1, sum(os.path.getsize(bin_file) for bin_file in bin_files))
  File "/opt/conda/envs/ptl-py310/lib/python3.10/site-packages/litgpt/scripts/convert_hf_checkpoint.py", line 525, in <genexpr>
    total_size = max(1, sum(os.path.getsize(bin_file) for bin_file in bin_files))
  File "/opt/conda/envs/ptl-py310/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/microsoft/Phi-3.5-mini-instruct/model-00001-of-00002.bin'`

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.4.11


```

**Comment by wasifferoze** [comment]
I find out you need to convert safetensor files to pytorch bin before using convert to litgpt command.
