### ISSUE TITLE
`litgpt download list` not working

### ISSUE THREAD

**Issue by a2jinhee** [Lightning-AI/litgpt#1783]
### Bug description

Somehow using lightning=2.4.0 doesn't work, so I'm using a stable version of 2.3.3
<img width="826" alt="image" src="https://github.com/user-attachments/assets/3b0e4a94-0e13-426e-8ee1-39d1f0688ac6">

But, this is the output of litgpt download list. Does anyone have the same issue? 

```
/home/jovyan/litgpt$ litgpt download list
Traceback (most recent call last):
  File "/home/a2jinhee/.local/bin/litgpt", line 5, in <module>
    from litgpt.__main__ import main
  File "/home/a2jinhee/.local/lib/python3.8/site-packages/litgpt/__init__.py", line 6, in <module>
    from litgpt.api import LLM
  File "/home/a2jinhee/.local/lib/python3.8/site-packages/litgpt/api.py", line 19, in <module>
    from litgpt.generate.sequentially import sequential
  File "/home/a2jinhee/.local/lib/python3.8/site-packages/litgpt/generate/sequentially.py", line 28, in <module>
    import litgpt.generate.base as generate_base
  File "/home/a2jinhee/.local/lib/python3.8/site-packages/litgpt/generate/base.py", line 81, in <module>
    def batched_sample(logits: list[torch.Tensor], kwargs: list[dict]) -> torch.Tensor:
TypeError: 'type' object is not subscriptable
```

### What operating system are you using?

ubuntu

### LitGPT Version

``` 
Version: 0.5.0.dev1


```

**Comment by a2jinhee** [comment]
Solved it by upgrading python: 3.8 → 3.9 !
