### ISSUE TITLE
MPSAccelerator cannot run on your system on Mac M1 pro

### ISSUE THREAD

**Issue by debasisdwivedy** [Lightning-AI/litgpt#1875]
Hi,

When i try to run the code as per the tutorial : 

```
from litgpt import LLM

llm = LLM.load("EleutherAI/pythia-14m")
text = llm.generate("Correct the spelling: Every summer, the familly enjoys a trip to the mountains.")
print(text)
```

I get the issue below:

```
Traceback (most recent call last):
  File "/Volumes/MacintoshDrive/Midships/huggingFace/litgpt/test.py", line 4, in <module>
    llm = LLM.load("EleutherAI/pythia-14m")
  File "/Volumes/MacintoshDrive/Midships/huggingFace/.adalflow_env/lib/python3.10/site-packages/litgpt/api.py", line 223, in load
    fabric = L.Fabric(
  File "/Volumes/MacintoshDrive/Midships/huggingFace/.adalflow_env/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 128, in __init__
    self._connector = _Connector(
  File "/Volumes/MacintoshDrive/Midships/huggingFace/.adalflow_env/lib/python3.10/site-packages/lightning/fabric/connector.py", line 145, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/Volumes/MacintoshDrive/Midships/huggingFace/.adalflow_env/lib/python3.10/site-packages/lightning/fabric/connector.py", line 349, in _set_parallel_devices_and_init_accelerator
    raise RuntimeError(
RuntimeError: `MPSAccelerator` can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Fabric`: ['cpu'].
```

I have tried running it with the options below:

- python <script.py>
- PYTORCH_ENABLE_MPS_FALLBACK=1 python <script.py>

This is as per documentation: https://lightning.ai/docs/pytorch/stable/accelerators/mps_basic.html

This is for all models microsoft/phi-2 etc.
Regards

**Comment by debasisdwivedy** [comment]
I found the issue here.

I had my python venv set up here. So i basically had to recreate it as it was creating problems, and reinstall litgpt :)
